# When does it trigger
name: echo
on:
  workflow_dispatch:
  push:
    branches:
      - main
  
# What does it do 
jobs:
  echo: # arbritry name
    name: echo a string
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Look! I'm a string!"
