name: Test files before PR

# Define when this job triggers
on:
  workflow_dispatch:
  pull_request:

# Define what job does
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install Python
        uses: actions/setup-python@v7
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run Tests
        run: pytest